version: '3'

services:
  mongo-1:
    image: mongo:4.4.1
    command:
      - --storageEngine
      - wiredTiger
      - --replSet
      - myRepl
    depends_on:
      - mongo-2
      - mongo-3
    restart: always

  mongo-2:
    image: mongo:4.4.1
    command:
      - --storageEngine
      - wiredTiger
      - --replSet
      - myRepl
    restart: always

  mongo-3:
    image: mongo:4.4.1
    command:
      - --storageEngine
      - wiredTiger
      - --replSet
      - myRepl
    restart: always

  web:
    build: .
    command: npm start
    ports:
      - '8000:5000'
    depends_on:
      - mongo-1
      - mongo-2
      - mongo-3
    volumes:
      - './src:/code/src'
    restart: always
